const en = {
  //Global
  watt: "W",
  quantity: "Quantity",
  deviceName: "Device name",
  workingHours: "Working hours",
  peakHours: "Peak hours",
  offPeakHours: "Off-peak hours",
  fillFields: "Please fill all fields",
  hour: "hour",
  hours: "hours",
  day: "day",
  night: "night",
  home: "Home",
  settings: "Settings",
  about: "About",
  yes: "Yes",
  no: "No",
  lightThemeSet: "Light theme set",
  darkThemeSet: "Dark theme set",
  report: "Report",
  perDay: "Per day",
  perWeek: "Per week",
  perMonth: "Per month",
  perYear: "Per year",
  welcome: "Welcome",
  selectCurrencyAndRatePlan: "Select currency and rate plan",
  continue: "Continue",

  //Settings
  main: "Main",
  ratePlan: 'Rate plan',
  language: 'Language',
  currency: 'Currency',
  darkTheme: 'Dark theme',
  choosePlan: 'Choose a plan',
  pricePerkWh: 'Price per kWh',
  planPeak: 'Price per peak',
  planOffPeak: 'Price per off-peak',
  resetSettings: 'Reset settings',
  planFixed: 'Fixed',
  planPeakOffpeak: 'Peak/off-peak',
  changePlan: "Change Plan",
  confirmDeviceDeletion: "All added devices will be deleted.",
  confirmReset: "Are you sure you want to reset the settings?",
  settingsReset: "Settings have been reset.",

  //About
  energyMaster: "Energy Master",
  version: "Version",
  rate: "Rate",
  rateApp: "Rate App",
  contact: "Contact",
  contactDeveloper: "Contact Developer",
  check: "Check",
  checkUpdates: "Check for Updates",
  copyright: "\u00A9 2023 Energy Master",
  
  //Home
  consumption: "Total Consumption:",
  deviceList: "Device List:",
  choosePrice: "Select the price per kWh in settings",
  addDevice: "Add device",
  add: "Add",
  deviceAdded: "Device has been added",

  //listItems
  deviceListEmpty: "Devices have not been added yet",
  deviceDeleted: "Device has been deleted",
  watts: "Power, W",
  quantityUnit: "pcs",
};
export default en;