const es = {
    //Global
    watt: "Vatio",
    quantity: "Cantidad",
    deviceName: "Nombre del dispositivo",
    workingHours: "Horas de trabajo",
    peakHours: "Horas pico",
    offPeakHours: "Horas fuera de pico",
    fillFields: "Por favor, complete todos los campos",
    hour: "hora",
    hours: "horas",
    day: "día",
    night: "noche",
    home: "Inicio",
    settings: "Configuración",
    about: "Acerca de",
    yes: "Sí",
    no: "No",
    lightThemeSet: "Tema claro establecido",
    darkThemeSet: "Tema oscuro establecido",
    report: "Informe",
    perDay: "Por día",
    perWeek: "Por semana",
    perMonth: "Por mes",
    perYear: "Por año",
  
    //Settings
    main: "Principal",
    ratePlan: "Plan de tarifas",
    language: "Idioma",
    currency: "Moneda",
    darkTheme: "Tema oscuro",
    choosePlan: "Elegir un plan",
    pricePerkWh: "Precio por kWh",
    planPeak: "Precio pico",
    planOffPeak: "Precio fuera de pico",
    resetSettings: "Restablecer configuración",
    planFixed: "Fijo",
    planPeakOffpeak: "Pico/fuera de pico",
    changePlan: "Cambiar plan",
    confirmDeviceDeletion: "Se eliminarán todos los dispositivos agregados.",
    confirmReset: "¿Está seguro de que desea restablecer la configuración?",
    settingsReset: "La configuración ha sido restablecida.",
  
    //About
    energyMaster: "Maestro de Energía",
    version: "Versión",
    rate: "Calificar",
    rateApp: "Calificar la aplicación",
    contact: "Contacto",
    contactDeveloper: "Contactar al desarrollador",
    check: "Verificar",
    checkUpdates: "Buscar actualizaciones",
    copyright: "\u00A9 2023 Maestro de Energía",
  
    //Home
    consumption: "Consumo total:",
    deviceList: "Lista de dispositivos:",
    choosePrice: "Seleccione el precio por kWh en la configuración",
    addDevice: "Agregar dispositivo",
    add: "Agregar",
    deviceAdded: "El dispositivo ha sido agregado",
  
    //listItems
    deviceListEmpty: "Todavía no se han agregado dispositivos",
    deviceDeleted: "El dispositivo ha sido eliminado",
    watts: "Potencia, Vatio",
    quantityUnit: "unidades",
  };
  export default es;