const fr = {
    //Global
    watt: "Watt",
    quantity: "Quantité",
    deviceName: "Nom de l'appareil",
    workingHours: "Heures de travail",
    peakHours: "Heures de pointe",
    offPeakHours: "Heures creuses",
    fillFields: "Veuillez remplir tous les champs",
    hour: "heure",
    hours: "heures",
    day: "jour",
    night: "nuit",
    home: "Accueil",
    settings: "Paramètres",
    about: "À propos",
    yes: "Oui",
    no: "Non",
    lightThemeSet: "Thème clair défini",
    darkThemeSet: "Thème sombre défini",
    report: "Rapport",
    perDay: "Par jour",
    perWeek: "Par semaine",
    perMonth: "Par mois",
    perYear: "Par an",
  
    //Settings
    main: "Principal",
    ratePlan: "Plan tarifaire",
    language: "Langue",
    currency: "Devise",
    darkTheme: "Thème sombre",
    choosePlan: "Choisir un plan",
    pricePerkWh: "Prix par kWh",
    planPeak: "Prix de pointe",
    planOffPeak: "Prix heures creuses",
    resetSettings: "Réinitialiser les paramètres",
    planFixed: "Fixe",
    planPeakOffpeak: "Heures de pointe/heures creuses",
    changePlan: "Changer de plan",
    confirmDeviceDeletion: "Tous les appareils ajoutés seront supprimés.",
    confirmReset: "Êtes-vous sûr de vouloir réinitialiser les paramètres ?",
    settingsReset: "Les paramètres ont été réinitialisés.",
  
    //About
    energyMaster: "Maître de l'Énergie",
    version: "Version",
    rate: "Évaluer",
    rateApp: "Évaluer l'application",
    contact: "Contact",
    contactDeveloper: "Contacter le développeur",
    check: "Vérifier",
    checkUpdates: "Vérifier les mises à jour",
    copyright: "\u00A9 2023 Maître de l'Énergie",
  
    //Home
    consumption: "Consommation totale :",
    deviceList: "Liste des appareils :",
    choosePrice: "Sélectionnez le prix par kWh dans les paramètres",
    addDevice: "Ajouter un appareil",
    add: "Ajouter",
    deviceAdded: "L'appareil a été ajouté",
  
    //listItems
    deviceListEmpty: "Aucun appareil n'a encore été ajouté",
    deviceDeleted: "L'appareil a été supprimé",
    watts: "Puissance, Watt",
    quantityUnit: "pièces",
  };
  export default fr;
  