const hi = {
    //Global
    watt: "वॉट",
    quantity: "मात्रा",
    deviceName: "डिवाइस का नाम",
    workingHours: "काम करने का समय",
    peakHours: "शीर्ष समय",
    offPeakHours: "शीर्ष समय के बाहर",
    fillFields: "कृपया सभी क्षेत्र भरें",
    hour: "घंटा",
    hours: "घंटे",
    day: "दिन",
    night: "रात",
    home: "होम",
    settings: "सेटिंग्स",
    about: "के बारे में",
    yes: "हां",
    no: "नहीं",
    lightThemeSet: "प्रकाशम थीम सेट की गई है",
    darkThemeSet: "डार्क थीम सेट की गई है",
    report: "रिपोर्ट",
    perDay: "प्रति दिन",
    perWeek: "प्रति सप्ताह",
    perMonth: "प्रति माह",
    perYear: "प्रति वर्ष",
  
    //Settings
    main: "मुख्य",
    ratePlan: "मूल्य योजना",
    language: "भाषा",
    currency: "मुद्रा",
    darkTheme: "डार्क थीम",
    choosePlan: "एक योजना चुनें",
    pricePerkWh: "किलोवॉट-घंटे प्रति मूल्य",
    planPeak: "शीर्षक समय कीमत",
    planOffPeak: "शीर्षक समय के बाहर कीमत",
    resetSettings: "सेटिंग्स रीसेट करें",
    planFixed: "स्थिर",
    planPeakOffpeak: "शीर्षक/शीर्ष समय के बाहर",
    changePlan: "योजना बदलें",
    confirmDeviceDeletion: "सभी जोड़े गए डिवाइस हटा दिए जाएंगे।",
    confirmReset: "क्या आप सेटिंग्स को वापस सेट करना चाहते हैं?",
    settingsReset: "सेटिंग्स रीसेट कर दी गई हैं।",
  
    //About
    energyMaster: "ऊर्जा मास्टर",
    version: "संस्करण",
    rate: "रेटिंग",
    rateApp: "ऐप की रेटिंग करें",
    contact: "संपर्क करें",
    contactDeveloper: "डेवलपर से संपर्क करें",
    check: "जाँच करें",
    checkUpdates: "अपडेट की जाँच करें",
    copyright: "\u00A9 2023 ऊर्जा मास्टर",
  
    //Home
    consumption: "कुल खपत:",
    deviceList: "डिवाइस सूची:",
    choosePrice: "सेटिंग्स में किलोवॉट-घंटे कीमत का चयन करें",
    addDevice: "डिवाइस जोड़ें",
    add: "जोड़ें",
    deviceAdded: "डिवाइस जोड़ दी गई है",
  
    //listItems
    deviceListEmpty: "अबतक कोई डिवाइस नहीं जोड़ा गया है",
    deviceDeleted: "डिवाइस हटा दी गई है",
    watts: "वाट, वॉट",
    quantityUnit: "इकाइयाँ",
  };
  export default hi;