const it = {
    //Global
    watt: "Watt",
    quantity: "Quantità",
    deviceName: "Nome dispositivo",
    workingHours: "Ore di lavoro",
    peakHours: "Ore di punta",
    offPeakHours: "Ore fuori punta",
    fillFields: "Si prega di compilare tutti i campi",
    hour: "ora",
    hours: "ore",
    day: "giorno",
    night: "notte",
    home: "Home",
    settings: "Impostazioni",
    about: "Informazioni",
    yes: "Sì",
    no: "No",
    lightThemeSet: "Tema chiaro impostato",
    darkThemeSet: "Tema scuro impostato",
    report: "Report",
    perDay: "Al giorno",
    perWeek: "Alla settimana",
    perMonth: "Al mese",
    perYear: "All'anno",
  
    //Settings
    main: "Principale",
    ratePlan: "Piano tariffario",
    language: "Lingua",
    currency: "Valuta",
    darkTheme: "Tema scuro",
    choosePlan: "Scegli un piano",
    pricePerkWh: "Prezzo per kWh",
    planPeak: "Prezzo di punta",
    planOffPeak: "Prezzo fuori punta",
    resetSettings: "Ripristina impostazioni",
    planFixed: "Fisso",
    planPeakOffpeak: "Punta/fuori punta",
    changePlan: "Cambia piano",
    confirmDeviceDeletion: "Tutti i dispositivi aggiunti verranno cancellati.",
    confirmReset: "Sei sicuro di voler ripristinare le impostazioni?",
    settingsReset: "Impostazioni ripristinate.",
  
    //About
    energyMaster: "Maestro dell'Energia",
    version: "Versione",
    rate: "Valuta",
    rateApp: "Valuta l'app",
    contact: "Contatto",
    contactDeveloper: "Contatta lo sviluppatore",
    check: "Verifica",
    checkUpdates: "Verifica aggiornamenti",
    copyright: "\u00A9 2023 Maestro dell'Energia",
  
    //Home
    consumption: "Consumo totale:",
    deviceList: "Elenco dispositivi:",
    choosePrice: "Seleziona il prezzo per kWh nelle impostazioni",
    addDevice: "Aggiungi dispositivo",
    add: "Aggiungi",
    deviceAdded: "Il dispositivo è stato aggiunto",
  
    //listItems
    deviceListEmpty: "Non sono stati ancora aggiunti dispositivi",
    deviceDeleted: "Il dispositivo è stato eliminato",
    watts: "Potenza, Watt",
    quantityUnit: "pezzi",
  };
  export default it;
  