const pt = {
    //Global
    watt: "Watt",
    quantity: "Quantidade",
    deviceName: "Nome do dispositivo",
    workingHours: "Horas de funcionamento",
    peakHours: "Horas de pico",
    offPeakHours: "Horas fora de pico",
    fillFields: "Por favor, preencha todos os campos",
    hour: "hora",
    hours: "horas",
    day: "dia",
    night: "noite",
    home: "Início",
    settings: "Configurações",
    about: "Sobre",
    yes: "Sim",
    no: "Não",
    lightThemeSet: "Tema claro definido",
    darkThemeSet: "Tema escuro definido",
    report: "Relatório",
    perDay: "Por dia",
    perWeek: "Por semana",
    perMonth: "Por mês",
    perYear: "Por ano",
    welcome: "Bem-vindo",
    selectCurrencyAndRatePlan: "Escolha a moeda e o plano tarifário",
    continue: "Continuar",
  
    //Settings
    main: "Principal",
    ratePlan: "Plano de tarifas",
    language: "Idioma",
    currency: "Moeda",
    darkTheme: "Tema escuro",
    choosePlan: "Escolher um plano",
    pricePerkWh: "Preço por kWh",
    planPeak: "Preço de pico",
    planOffPeak: "Preço fora de pico",
    resetSettings: "Redefinir configurações",
    planFixed: "Fixo",
    planPeakOffpeak: "Pico/fora de pico",
    changePlan: "Alterar plano",
    confirmDeviceDeletion: "Todos os dispositivos adicionados serão excluídos.",
    confirmReset: "Tem certeza de que deseja redefinir as configurações?",
    settingsReset: "As configurações foram redefinidas.",
  
    //About
    energyMaster: "Mestre da Energia",
    version: "Versão",
    rate: "Avaliar",
    rateApp: "Avaliar o aplicativo",
    contact: "Contato",
    contactDeveloper: "Contatar o desenvolvedor",
    check: "Verificar",
    checkUpdates: "Verificar atualizações",
    copyright: "\u00A9 2023 Mestre da Energia",
  
    //Home
    consumption: "Consumo total:",
    deviceList: "Lista de dispositivos:",
    choosePrice: "Selecione o preço por kWh nas configurações",
    addDevice: "Adicionar dispositivo",
    add: "Adicionar",
    deviceAdded: "O dispositivo foi adicionado",
  
    //listItems
    deviceListEmpty: "Dispositivos ainda não foram adicionados",
    deviceDeleted: "O dispositivo foi excluído",
    watts: "Potência, Watt",
    quantityUnit: "unidades",
  };
  export default pt;
  