const ru = {
  //Global
  watt: "Вт",
  quantity: "Количество",
  deviceName: "Имя электроустройства",
  workingHours: "Время работы",
  peakHours: "Время работы в пик",
  offPeakHours: "Время работы ночью",
  fillFields: "Заполните все поля",
  hour: "час",
  hours: "ч.",
  day: "днем",
  night: "ночью",
  home: "Главная",
  settings: "Настройки",
  about: "О программе",
  yes: "Да",
  no: "Нет",
  lightThemeSet: "Установлена светлая тема",
  darkThemeSet: "Установлена темная тема",
  report: "Отчет",
  perDay: "В день",
  perWeek: "В неделю",
  perMonth: "В месяц",
  perYear: "В год",

  //Settings
  main: "Основные",
  ratePlan: 'Тарифный план',
  language: 'Язык',
  currency: 'Валюта',
  darkTheme: 'Темная тема',
  choosePlan: 'Выбрать план',
  pricePerkWh: 'Цена за Кв*ч',
  planPeak: 'Пиковая цена',
  planOffPeak: 'Внепиковая цена',
  resetSettings: 'Сбросить настройки',
  planFixed: 'Однотарифный',
  planPeakOffpeak: 'Двутарифный',
  changePlan: "Изменить план",
  confirmDeviceDeletion: "Все добавленные устройства будут удалены.",
  confirmReset: "Вы уверены, что хотите сбросить настройки?",
  settingsReset: "Настройки были сброшены.",

  //About
  energyMaster: "Energy Master",
  version: "Версия",
  rate: "Оценить",
  rateApp: "Оценить приложение",
  contact: "Связь",
  contactDeveloper: "Связаться с разработчиком",
  check: "Проверить",
  checkUpdates: "Проверить обновления",
  copyright: "\u00A9 2023 Energy Master",
  
  //Home
  consumption: "Общее потребление:",
  deviceList: "Список устройств:",
  choosePrice: "Выберите цену за кВт в настройках",
  addDevice: "Добавить электроустройство",
  add: "Добавить",
  deviceAdded: "Устройство было добавлено",

  //listItems
  deviceListEmpty: "Устройства еще не были добавлены",
  deviceDeleted: "Устройство было удалено",
  watts: "Мощность, Вт",
  quantityUnit: "шт.",

};
export default ru;