const zh = {
    //Global
    watt: "瓦特",
    quantity: "数量",
    deviceName: "设备名称",
    workingHours: "工作时间",
    peakHours: "高峰时段",
    offPeakHours: "非高峰时段",
    fillFields: "请填写所有字段",
    hour: "小时",
    hours: "小时",
    day: "白天",
    night: "晚上",
    home: "首页",
    settings: "设置",
    about: "关于",
    yes: "是",
    no: "否",
    lightThemeSet: "已选择浅色主题",
    darkThemeSet: "已选择深色主题",
    report: "报告",
    perDay: "每天",
    perWeek: "每周",
    perMonth: "每月",
    perYear: "每年",
    welcome: "欢迎",
    selectCurrencyAndRatePlan: "选择货币和费率计划",
    continue: "继续",
  
    //Settings
    main: "主要",
    ratePlan: "费率计划",
    language: "语言",
    currency: "货币",
    darkTheme: "深色主题",
    choosePlan: "选择计划",
    pricePerkWh: "每千瓦时价格",
    planPeak: "高峰价格",
    planOffPeak: "非高峰价格",
    resetSettings: "重置设置",
    planFixed: "固定",
    planPeakOffpeak: "高峰/非高峰",
    changePlan: "更改计划",
    confirmDeviceDeletion: "所有添加的设备将被删除。",
    confirmReset: "确定要重置设置吗？",
    settingsReset: "设置已重置。",
  
    //About
    energyMaster: "能源大师",
    version: "版本",
    rate: "评分",
    rateApp: "评价应用",
    contact: "联系",
    contactDeveloper: "联系开发者",
    check: "检查",
    checkUpdates: "检查更新",
    copyright: "\u00A9 2023 能源大师",
  
    //Home
    consumption: "总消耗：",
    deviceList: "设备列表：",
    choosePrice: "在设置中选择每千瓦时价格",
    addDevice: "添加设备",
    add: "添加",
    deviceAdded: "设备已添加",
  
    //listItems
    deviceListEmpty: "尚未添加设备",
    deviceDeleted: "设备已删除",
    watts: "功率，瓦特",
    quantityUnit: "件",
  };
  export default zh;